-- Enable Row Level Security (RLS) if needed, for now we keep it open or policy-based.
-- For a quick prototype, we might skip complex RLS, but standard practice is good.

-- 1. Settings Table
CREATE TABLE settings (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  logo_url TEXT,
  primary_color TEXT DEFAULT '#000000',
  secondary_color TEXT DEFAULT '#ffffff',
  game_title TEXT DEFAULT 'Quiz Game',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default row
INSERT INTO settings (id, logo_url) VALUES (1, '');

-- 2. Questions Table
CREATE TABLE questions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  question_text TEXT NOT NULL,
  options JSONB NOT NULL, -- Array of 4 strings
  correct_option INT NOT NULL CHECK (correct_option BETWEEN 0 AND 3),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Players Table
CREATE TABLE players (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  nickname TEXT UNIQUE NOT NULL,
  score INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Game Control Table
CREATE TABLE game_control (
  id INT PRIMARY KEY DEFAULT 1 CHECK (id = 1), -- Singleton row
  active_question_id UUID REFERENCES questions(id) ON DELETE SET NULL,
  is_active BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default row
INSERT INTO game_control (id, is_active) VALUES (1, FALSE);

-- Enable Realtime for specific tables
ALTER PUBLICATION supabase_realtime ADD TABLE game_control;
ALTER PUBLICATION supabase_realtime ADD TABLE players;

-- Storage Bucket for Branding
insert into storage.buckets (id, name, public) values ('branding', 'branding', true);
